import { PGlite } from 'npm:@electric-sql/pglite@0.3.14';
import { assertEquals, assertRejects } from 'jsr:@std/assert@1';
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',cap='00000000-0000-4000-8000-000000000010';
async function fixture(){const db=new PGlite();await db.exec(`create role authenticated;create role anon;create role service_role;create schema auth;
 create table auth.users(id uuid primary key);insert into auth.users values('${a}'),('${b}');
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.sub',true),'')::uuid$$;
 create table eligible(id uuid primary key);insert into eligible values('${a}');
 create function has_pro_entitlement(u uuid) returns boolean language sql as $$select exists(select 1 from eligible where id=u)$$;
 create table items(id uuid primary key,user_id uuid,url text,title text,text_content text,text_selector jsonb,type text,favorite boolean,status text,return_at timestamptz,created_at timestamptz,updated_at timestamptz,origin_installation_id uuid,deleted_at timestamptz);
 create table item_metadata(item_id uuid primary key references items(id) on delete cascade,user_id uuid,domain text,site_name text,title text,description text,favicon_url text,preview_image_url text,status text,content_type text,classification_source text,structured_data jsonb,created_at timestamptz,updated_at timestamptz);
 grant usage on schema auth to authenticated;grant select on items to authenticated;`);await db.exec(await Deno.readTextFile(new URL('../migrations/202610060001_extension_content.sql',import.meta.url)));return db;}
async function save(db:PGlite,owner=a,markdown='# Snapshot'){const item={id:crypto.randomUUID(),title:'Saved',url:'https://example.com',status:'inbox'};return (await db.query<{id:string}>('select save_extension_capture($1,$2,$3::jsonb,null,$4::jsonb) as id',[owner,cap,JSON.stringify(item),JSON.stringify({kind:'page',markdown})])).rows[0].id;}
Deno.test('migration: snapshots are atomic, paid, deduplicated and cascade on delete',async()=>{const db=await fixture();try{const [first,second]=await Promise.all([save(db),save(db)]);assertEquals(first,second);assertEquals((await db.query('select * from items')).rows.length,1);assertEquals((await db.query('select * from item_content')).rows.length,1);await assertRejects(()=>save(db,b));await db.exec(`delete from items`);assertEquals((await db.query('select * from item_content')).rows.length,0);await assertRejects(()=>save(db,a,'x'.repeat(204801)));assertEquals((await db.query('select * from items')).rows.length,0);}finally{await db.close();}});
Deno.test('migration: account-owned read only snapshots; clients cannot call server RPC',async()=>{const db=await fixture();try{await save(db);await db.exec(`select set_config('request.sub','${a}',false);set role authenticated;`);assertEquals((await db.query('select * from item_content')).rows.length,1);await assertRejects(()=>save(db));await db.exec(`select set_config('request.sub','${b}',false);`);assertEquals((await db.query('select * from item_content')).rows.length,0);await assertRejects(()=>db.exec(`delete from item_content`));}finally{await db.close();}});
