// Auto-generated by scripts/bump_version.js on every build/deploy
export const APP_VERSION = '1.0.176';
export const MAJOR_VERSION = 1;
export const MINOR_VERSION = 0;
export const PATCH_VERSION = 176;
export const BUILD_NUMBER = 178;
export const BUILD_TIME = '2026-10-08T07:09:10.188Z';

export const VERSION_METADATA = {
  app: 'laterbox',
  version: APP_VERSION,
  major: MAJOR_VERSION,
  minor: MINOR_VERSION,
  patch: PATCH_VERSION,
  buildNumber: BUILD_NUMBER,
  buildTime: BUILD_TIME,
} as const;
