// Auto-generated by scripts/bump_version.js on every build/deploy
export const APP_VERSION = '1.0.84';
export const MAJOR_VERSION = 1;
export const MINOR_VERSION = 0;
export const PATCH_VERSION = 84;
export const BUILD_NUMBER = 85;
export const BUILD_TIME = '2026-08-25T17:00:16.250Z';

export const VERSION_METADATA = {
  app: 'laterbox',
  version: APP_VERSION,
  major: MAJOR_VERSION,
  minor: MINOR_VERSION,
  patch: PATCH_VERSION,
  buildNumber: BUILD_NUMBER,
  buildTime: BUILD_TIME,
} as const;
