// Auto-generated by scripts/bump-version.js on every build/deploy
export const APP_VERSION = '1.0.1';
export const MAJOR_VERSION = 1;
export const MINOR_VERSION = 0;
export const PATCH_VERSION = 1;
export const BUILD_NUMBER = 2;
export const BUILD_TIME = '2026-08-23T08:44:11.915Z';

export const VERSION_METADATA = {
  app: 'laterbox-web',
  version: APP_VERSION,
  major: MAJOR_VERSION,
  minor: MINOR_VERSION,
  patch: PATCH_VERSION,
  buildNumber: BUILD_NUMBER,
  buildTime: BUILD_TIME,
} as const;
