// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDco-fthFjekoIsLGB_UuIhHsc9bNd4XYw',
    appId: '1:742276864633:web:87ec9451c1a5689e6912a8',
    messagingSenderId: '742276864633',
    projectId: 'laterbox-9210c',
    authDomain: 'laterbox-9210c.firebaseapp.com',
    storageBucket: 'laterbox-9210c.firebasestorage.app',
    measurementId: 'G-M5M4D17XTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADL2jLcBO1iIVytvHJOx4kr5MMJkzdNes',
    appId: '1:742276864633:android:b34aeb0326d1a81b6912a8',
    messagingSenderId: '742276864633',
    projectId: 'laterbox-9210c',
    storageBucket: 'laterbox-9210c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCndp5dLU_Gld79_uaZg1W4V4CaRz1j7TE',
    appId: '1:742276864633:ios:3c0996f7a90269486912a8',
    messagingSenderId: '742276864633',
    projectId: 'laterbox-9210c',
    storageBucket: 'laterbox-9210c.firebasestorage.app',
    iosBundleId: 'pro.micorp.laterbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCndp5dLU_Gld79_uaZg1W4V4CaRz1j7TE',
    appId: '1:742276864633:ios:3c0996f7a90269486912a8',
    messagingSenderId: '742276864633',
    projectId: 'laterbox-9210c',
    storageBucket: 'laterbox-9210c.firebasestorage.app',
    iosBundleId: 'pro.micorp.laterbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDco-fthFjekoIsLGB_UuIhHsc9bNd4XYw',
    appId: '1:742276864633:web:87ec9451c1a5689e6912a8',
    messagingSenderId: '742276864633',
    projectId: 'laterbox-9210c',
    authDomain: 'laterbox-9210c.firebaseapp.com',
    storageBucket: 'laterbox-9210c.firebasestorage.app',
    measurementId: 'G-M5M4D17XTK',
  );
}
