import {test} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {findInstagramPosts} from '../src/content/social';
import {createInstagramControls} from '../src/content/instagram-controls';
const post=(id:string)=>`<article><header><a>Writer ${id}</a></header><p>Caption ${id}</p><img src="/${id}.jpg"><a href="/p/${id}/"><time datetime="2026-10-06">Today</time></a><section><button aria-label="Like">Like</button><span><button><svg aria-label="Share"></svg></button></span><button>Bookmark</button></section></article>`;
const fixture=(html:string,url='https://www.instagram.com/')=>new JSDOM(html,{url});
test('feed posts return their own source and Share action slot',()=>{const {window:w}=fixture(post('one')+post('two'));const posts=findInstagramPosts(w.document,w.location.href);assert.equal(posts.length,2);assert.equal(posts[0].url,'https://www.instagram.com/p/one/');assert.equal(posts[1].author,'Writer two');assert.equal(posts[0].insertionPoint.tagName,'SPAN');assert.equal(posts[0].publishedAt,'2026-10-06');});
test('post dialogs and standalone Reels use their own content root',()=>{for(const [path,html] of [['/p/one/','<div role="dialog"><article><p>Caption</p><img src="/preview.jpg"><button aria-label="Share post"></button></article></div>'],['/reel/two/','<main><div><video poster="/reel.jpg"></video><p>Reel caption</p><section><button aria-label="Share reel"></button></section></div></main>']]){const {window:w}=fixture(html,'https://www.instagram.com'+path);const posts=findInstagramPosts(w.document,w.location.href);assert.equal(posts.length,1);assert.equal(new URL(posts[0].url).pathname,path);assert.ok(!posts[0].root.matches('body'));}});
test('unsupported, ambiguous, missing Share and Stories get no injected controls',()=>{for(const html of ['<article><a href="/p/a/">Post</a></article>','<article><button aria-label="Share"></button></article>','<article><a href="/p/a/">A</a><a href="/p/b/">B</a><button aria-label="Share"></button></article>']){const {window:w}=fixture(html);assert.equal(findInstagramPosts(w.document,w.location.href).length,0);}const {window:w}=fixture(post('one'),'https://www.instagram.com/stories/author/1/');assert.equal(findInstagramPosts(w.document,w.location.href).length,0);assert.equal(findInstagramPosts(w.document,'https://x.com/home').length,0);});
test('reconciliation places one button beside Share, replaces recycled posts and disables cleanly',()=>{const {window:w}=fixture(post('one')+post('two'));const resolvers:(()=>any)[]=[];const sync=createInstagramControls(w.document,(_post,resolve)=>{resolvers.push(resolve);const el=w.document.createElement('span');el.setAttribute('data-laterbox-control','');el.textContent='Save to LaterBox';return el;});sync(true,w.location.href);sync(true,w.location.href);assert.equal(w.document.querySelectorAll('[data-laterbox-control]').length,2);const posts=findInstagramPosts(w.document,w.location.href);assert.equal(posts[0].insertionPoint.nextElementSibling?.textContent,'Save to LaterBox');w.document.querySelector('a[href]')!.setAttribute('href','/p/recycled/');assert.equal(resolvers[0](),undefined);sync(true,w.location.href);assert.equal(w.document.querySelectorAll('[data-laterbox-control]').length,2);assert.equal(resolvers.at(-1)!().url,'https://www.instagram.com/p/recycled/');w.document.querySelector('article')!.remove();sync(true,w.location.href);assert.equal(w.document.querySelectorAll('[data-laterbox-control]').length,1);sync(false,w.location.href);assert.equal(w.document.querySelectorAll('[data-laterbox-control]').length,0);sync(true,w.location.href);assert.equal(w.document.querySelectorAll('[data-laterbox-control]').length,1);w.history.pushState({},'','/stories/author/1/');sync(true,w.location.href);assert.equal(w.document.querySelectorAll('[data-laterbox-control]').length,0);});

test('compiled controls isolate clicks, preserve keyboard focus, and show save feedback',async()=>{
 const {build}=await import('vite');const w=new JSDOM(post('one')+post('two'),{url:'https://www.instagram.com/',runScripts:'outside-only'}).window;
 const shadows:ShadowRoot[]=[];const attach=w.Element.prototype.attachShadow;
 w.Element.prototype.attachShadow=function(options){const shadow=attach.call(this,options);shadows.push(shadow);return shadow;};
 let saves=0,shares=0;let captured:any;w.document.querySelector('section')!.addEventListener('click',()=>shares++);
 (w as any).chrome={storage:{local:{get:async()=>({injectedControls:true})},onChanged:{addListener:()=>{}}},runtime:{sendMessage:async(message:any)=>{saves++;captured=message.capture;return {status:'saved'}}}};
 // Native trusted clicks are a browser check; fixture-only instrumentation lets
 // this compiled UI exercise its save states without contacting an account.
 const result=await build({configFile:false,publicDir:false,logLevel:'silent',build:{write:false,lib:{entry:new URL('../src/content/index.ts',import.meta.url).pathname,name:'FixtureControls',formats:['iife']}}});
 const bundle=Array.isArray(result) ? result[0] : result;
 const chunk=(bundle as any).output.find((entry:any)=>entry.type==='chunk');const script=chunk.code.replace(/([a-zA-Z_$][\w$]*)\.isTrusted/g,'true');
 w.eval(script);await new Promise(resolve=>setTimeout(resolve,10));
 const controls=Array.from(w.document.querySelectorAll('[data-laterbox-control]')).filter(el=>el.tagName==='SPAN');assert.equal(controls.length,2);
 const button=shadows.find(shadow=>shadow.host===controls[0])!.querySelector('button')!;assert.equal(button.getAttribute('type'),'button');assert.match(button.getAttribute('aria-label')!,/Writer one/);button.focus();assert.equal(w.document.activeElement,controls[0]);button.click();assert.equal(shares,0);assert.equal(button.getAttribute('aria-busy'),'true');await new Promise(resolve=>setTimeout(resolve,10));assert.equal(saves,1);assert.equal(captured.url,'https://www.instagram.com/p/one/');assert.ok(captured.markdown.includes('Caption one'));assert.ok(!captured.markdown.includes('Caption two'));assert.equal(captured.author,'Writer one');assert.equal(captured.previewImageUrl,'https://www.instagram.com/one.jpg');assert.equal(button.dataset.state,'saved');assert.match(button.textContent!,/Saved/);w.close();
});
