#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const versionJsonPath = path.join(rootDir, 'version.json');
const publicVersionJsonPath = path.join(rootDir, 'public', 'version.json');
const versionTsPath = path.join(rootDir, 'src', 'lib', 'version.ts');

function loadVersionConfig() {
  if (fs.existsSync(versionJsonPath)) {
    try {
      return JSON.parse(fs.readFileSync(versionJsonPath, 'utf8'));
    } catch {
      // ignore
    }
  }
  return {
    major: 1,
    minor: 0,
    patch: 0,
    version: '1.0.0',
    buildNumber: 1,
  };
}

function bumpVersion() {
  const current = loadVersionConfig();

  let major = typeof current.major === 'number' ? current.major : 1;
  let minor = typeof current.minor === 'number' ? current.minor : 0;
  let patch = typeof current.patch === 'number' ? current.patch : 0;
  let buildNumber = typeof current.buildNumber === 'number' ? current.buildNumber : 1;

  // Check if user manually edited version string e.g. "2.0.0" or "2.1.0"
  if (current.version && typeof current.version === 'string') {
    const parts = current.version.split('.').map((p) => parseInt(p, 10));
    if (parts.length >= 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
      if (parts[0] !== major || parts[1] !== minor) {
        // User changed major or minor manually!
        major = parts[0];
        minor = parts[1];
        patch = 0; // Reset patch for the new major/minor series
      }
    }
  }

  // Increment patch for this build/deploy
  patch += 1;
  buildNumber += 1;
  const versionString = `${major}.${minor}.${patch}`;
  const buildTime = new Date().toISOString();

  const versionData = {
    major,
    minor,
    patch,
    version: versionString,
    buildNumber,
    buildTime,
  };

  // 1. Write laterbox-web/version.json
  fs.writeFileSync(versionJsonPath, JSON.stringify(versionData, null, 2) + '\n', 'utf8');

  // 2. Write laterbox-web/public/version.json
  const publicData = {
    app: 'laterbox-web',
    version: versionString,
    major,
    minor,
    patch,
    buildNumber,
    buildTime,
  };
  fs.writeFileSync(publicVersionJsonPath, JSON.stringify(publicData, null, 2) + '\n', 'utf8');

  // 3. Write laterbox-web/src/lib/version.ts
  const tsContent = `// Auto-generated by scripts/bump-version.js on every build/deploy
export const APP_VERSION = '${versionString}';
export const MAJOR_VERSION = ${major};
export const MINOR_VERSION = ${minor};
export const PATCH_VERSION = ${patch};
export const BUILD_NUMBER = ${buildNumber};
export const BUILD_TIME = '${buildTime}';

export const VERSION_METADATA = {
  app: 'laterbox-web',
  version: APP_VERSION,
  major: MAJOR_VERSION,
  minor: MINOR_VERSION,
  patch: PATCH_VERSION,
  buildNumber: BUILD_NUMBER,
  buildTime: BUILD_TIME,
} as const;
`;
  fs.writeFileSync(versionTsPath, tsContent, 'utf8');

  console.log(`[LaterBox Version] Bumped to v${versionString} (build #${buildNumber}) at ${buildTime}`);
}

bumpVersion();
