#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');

const rootVersionJsonPath = path.join(rootDir, 'version.json');
const pubspecPath = path.join(rootDir, 'pubspec.yaml');
const webVersionJsonPath = path.join(rootDir, 'laterbox-web', 'version.json');
const webPublicVersionJsonPath = path.join(rootDir, 'laterbox-web', 'public', 'version.json');
const webVersionTsPath = path.join(rootDir, 'laterbox-web', 'src', 'lib', 'version.ts');
const extensionPackageJsonPath = path.join(rootDir, 'extension', 'package.json');
const extensionChromiumManifestPath = path.join(rootDir, 'extension', 'manifests', 'chromium.json');
const extensionFirefoxManifestPath = path.join(rootDir, 'extension', 'manifests', 'firefox.json');
const extensionSafariManifestPath = path.join(rootDir, 'extension', 'manifests', 'safari.json');
const innoSetupPath = path.join(rootDir, 'scripts', 'laterbox.iss');

function loadVersion() {
  if (fs.existsSync(rootVersionJsonPath)) {
    try {
      return JSON.parse(fs.readFileSync(rootVersionJsonPath, 'utf8'));
    } catch {
      // ignore
    }
  }
  if (fs.existsSync(webVersionJsonPath)) {
    try {
      return JSON.parse(fs.readFileSync(webVersionJsonPath, 'utf8'));
    } catch {
      // ignore
    }
  }
  return {
    major: 1,
    minor: 0,
    patch: 0,
    version: '1.0.0',
    buildNumber: 1,
  };
}

function bumpVersion() {
  const args = process.argv.slice(2);
  let manualVersion = null;
  if (args.length > 0) {
    if (args[0] === '--set' && args[1]) {
      manualVersion = args[1];
    } else if (!args[0].startsWith('-')) {
      manualVersion = args[0];
    }
  }

  const current = loadVersion();
  let major = typeof current.major === 'number' ? current.major : 1;
  let minor = typeof current.minor === 'number' ? current.minor : 0;
  let patch = typeof current.patch === 'number' ? current.patch : 0;
  let buildNumber = typeof current.buildNumber === 'number' ? current.buildNumber : 1;

  if (manualVersion) {
    const parts = manualVersion.replace(/^v/, '').split('.').map((p) => parseInt(p, 10));
    major = !isNaN(parts[0]) ? parts[0] : major;
    minor = !isNaN(parts[1]) ? parts[1] : 0;
    patch = !isNaN(parts[2]) ? parts[2] : 0;
  } else {
    // Check if user manually changed version in version.json
    if (current.version && typeof current.version === 'string') {
      const parts = current.version.replace(/^v/, '').split('.').map((p) => parseInt(p, 10));
      if (parts.length >= 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
        if (parts[0] !== major || parts[1] !== minor) {
          major = parts[0];
          minor = parts[1];
          patch = 0;
        }
      }
    }
    patch += 1;
  }

  buildNumber += 1;
  const versionString = `${major}.${minor}.${patch}`;
  const flutterVersionString = `${versionString}+${buildNumber}`;
  const buildTime = new Date().toISOString();

  const versionData = {
    major,
    minor,
    patch,
    version: versionString,
    buildNumber,
    buildTime,
  };

  // 1. Root version.json
  fs.writeFileSync(rootVersionJsonPath, JSON.stringify(versionData, null, 2) + '\n', 'utf8');

  // 2. pubspec.yaml (Flutter Mobile & Desktop)
  if (fs.existsSync(pubspecPath)) {
    let pubspec = fs.readFileSync(pubspecPath, 'utf8');
    pubspec = pubspec.replace(/^version:\s*.+$/m, `version: ${flutterVersionString}`);
    fs.writeFileSync(pubspecPath, pubspec, 'utf8');
  }

  // 3. laterbox-web/version.json
  if (fs.existsSync(path.dirname(webVersionJsonPath))) {
    fs.writeFileSync(webVersionJsonPath, JSON.stringify(versionData, null, 2) + '\n', 'utf8');
  }

  // 4. laterbox-web/public/version.json
  if (fs.existsSync(path.dirname(webPublicVersionJsonPath))) {
    const publicData = {
      app: 'laterbox-web',
      version: versionString,
      major,
      minor,
      patch,
      buildNumber,
      buildTime,
    };
    fs.writeFileSync(webPublicVersionJsonPath, JSON.stringify(publicData, null, 2) + '\n', 'utf8');
  }

  // 5. laterbox-web/src/lib/version.ts
  if (fs.existsSync(path.dirname(webVersionTsPath))) {
    const tsContent = `// Auto-generated by scripts/bump_version.js on every build/deploy
export const APP_VERSION = '${versionString}';
export const MAJOR_VERSION = ${major};
export const MINOR_VERSION = ${minor};
export const PATCH_VERSION = ${patch};
export const BUILD_NUMBER = ${buildNumber};
export const BUILD_TIME = '${buildTime}';

export const VERSION_METADATA = {
  app: 'laterbox',
  version: APP_VERSION,
  major: MAJOR_VERSION,
  minor: MINOR_VERSION,
  patch: PATCH_VERSION,
  buildNumber: BUILD_NUMBER,
  buildTime: BUILD_TIME,
} as const;
`;
    fs.writeFileSync(webVersionTsPath, tsContent, 'utf8');
  }

  // 6. extension/package.json
  if (fs.existsSync(extensionPackageJsonPath)) {
    try {
      const extPkg = JSON.parse(fs.readFileSync(extensionPackageJsonPath, 'utf8'));
      extPkg.version = versionString;
      fs.writeFileSync(extensionPackageJsonPath, JSON.stringify(extPkg, null, 2) + '\n', 'utf8');
    } catch {
      // ignore
    }
  }

  // 7. extension manifests (Chromium, Firefox, Safari)
  const manifests = [extensionChromiumManifestPath, extensionFirefoxManifestPath, extensionSafariManifestPath];
  for (const mPath of manifests) {
    if (fs.existsSync(mPath)) {
      try {
        const manifest = JSON.parse(fs.readFileSync(mPath, 'utf8'));
        manifest.version = versionString;
        fs.writeFileSync(mPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
      } catch {
        // ignore
      }
    }
  }

  // 8. scripts/laterbox.iss (Windows Inno Setup Installer)
  if (fs.existsSync(innoSetupPath)) {
    let iss = fs.readFileSync(innoSetupPath, 'utf8');
    iss = iss.replace(/#define\s+AppVersion\s+"[^"]+"/g, `#define AppVersion "${versionString}"`);
    fs.writeFileSync(innoSetupPath, iss, 'utf8');
  }

  console.log(`[LaterBox Version] Synchronized version across Mobile, Desktop, Web & Extensions: v${versionString} (build #${buildNumber})`);
}

bumpVersion();
