#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');

const rootVersionJsonPath = path.join(rootDir, 'version.json');
const webVersionJsonPath = path.join(rootDir, 'laterbox-web', 'version.json');
const webPublicVersionJsonPath = path.join(rootDir, 'laterbox-web', 'public', 'version.json');
const webVersionTsPath = path.join(rootDir, 'laterbox-web', 'src', 'lib', 'version.ts');
const extensionPackageJsonPath = path.join(rootDir, 'extension', 'package.json');
const extensionChromiumManifestPath = path.join(rootDir, 'extension', 'manifests', 'chromium.json');
const extensionFirefoxManifestPath = path.join(rootDir, 'extension', 'manifests', 'firefox.json');
const extensionSafariManifestPath = path.join(rootDir, 'extension', 'manifests', 'safari.json');
const iosPbxprojPath = path.join(rootDir, 'laterbox-ios', 'laterbox-ios.xcodeproj', 'project.pbxproj');
const iosAppVersionSwiftPath = path.join(rootDir, 'laterbox-ios', 'laterbox-ios', 'AppVersion.swift');
const iosShareInfoPlistPath = path.join(rootDir, 'laterbox-ios', 'LaterBoxShare', 'Info.plist');

function loadVersion() {
  if (fs.existsSync(rootVersionJsonPath)) {
    try {
      return JSON.parse(fs.readFileSync(rootVersionJsonPath, 'utf8'));
    } catch {
      // ignore
    }
  }
  if (fs.existsSync(webVersionJsonPath)) {
    try {
      return JSON.parse(fs.readFileSync(webVersionJsonPath, 'utf8'));
    } catch {
      // ignore
    }
  }
  return {
    major: 1,
    minor: 0,
    patch: 0,
    version: '1.0.0',
    buildNumber: 1,
  };
}

function bumpVersion() {
  const args = process.argv.slice(2);
  let manualVersion = null;
  let syncOnly = false;
  if (args.length > 0) {
    if (args[0] === '--set' && args[1]) {
      manualVersion = args[1];
    } else if (args[0] === '--sync-only' || args[0] === '--sync') {
      syncOnly = true;
    } else if (!args[0].startsWith('-')) {
      manualVersion = args[0];
    }
  }

  const current = loadVersion();
  let major = typeof current.major === 'number' ? current.major : 1;
  let minor = typeof current.minor === 'number' ? current.minor : 0;
  let patch = typeof current.patch === 'number' ? current.patch : 0;
  let buildNumber = typeof current.buildNumber === 'number' ? current.buildNumber : 1;

  if (!syncOnly) {
    if (manualVersion) {
      const parts = manualVersion.replace(/^v/, '').split('.').map((p) => parseInt(p, 10));
      major = !isNaN(parts[0]) ? parts[0] : major;
      minor = !isNaN(parts[1]) ? parts[1] : 0;
      patch = !isNaN(parts[2]) ? parts[2] : 0;
    } else {
      // Check if user manually changed version in version.json
      if (current.version && typeof current.version === 'string') {
        const parts = current.version.replace(/^v/, '').split('.').map((p) => parseInt(p, 10));
        if (parts.length >= 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
          if (parts[0] !== major || parts[1] !== minor) {
            major = parts[0];
            minor = parts[1];
            patch = 0;
          }
        }
      }
      patch += 1;
    }

    buildNumber += 1;
  }

  const versionString = `${major}.${minor}.${patch}`;
  const buildTime = syncOnly && current.buildTime ? current.buildTime : new Date().toISOString();

  const versionData = {
    major,
    minor,
    patch,
    version: versionString,
    buildNumber,
    buildTime,
  };

  // 1. Root version.json
  fs.writeFileSync(rootVersionJsonPath, JSON.stringify(versionData, null, 2) + '\n', 'utf8');

  // 3. laterbox-web/version.json
  if (fs.existsSync(path.dirname(webVersionJsonPath))) {
    fs.writeFileSync(webVersionJsonPath, JSON.stringify(versionData, null, 2) + '\n', 'utf8');
  }

  // 4. laterbox-web/public/version.json
  if (fs.existsSync(path.dirname(webPublicVersionJsonPath))) {
    const publicData = {
      app: 'laterbox-web',
      version: versionString,
      major,
      minor,
      patch,
      buildNumber,
      buildTime,
    };
    fs.writeFileSync(webPublicVersionJsonPath, JSON.stringify(publicData, null, 2) + '\n', 'utf8');
  }

  // 5. laterbox-web/src/lib/version.ts
  if (fs.existsSync(path.dirname(webVersionTsPath))) {
    const tsContent = `// Auto-generated by scripts/bump_version.js on every build/deploy
export const APP_VERSION = '${versionString}';
export const MAJOR_VERSION = ${major};
export const MINOR_VERSION = ${minor};
export const PATCH_VERSION = ${patch};
export const BUILD_NUMBER = ${buildNumber};
export const BUILD_TIME = '${buildTime}';

export const VERSION_METADATA = {
  app: 'laterbox',
  version: APP_VERSION,
  major: MAJOR_VERSION,
  minor: MINOR_VERSION,
  patch: PATCH_VERSION,
  buildNumber: BUILD_NUMBER,
  buildTime: BUILD_TIME,
} as const;
`;
    fs.writeFileSync(webVersionTsPath, tsContent, 'utf8');
  }

  // 6. extension/package.json
  if (fs.existsSync(extensionPackageJsonPath)) {
    try {
      const extPkg = JSON.parse(fs.readFileSync(extensionPackageJsonPath, 'utf8'));
      extPkg.version = versionString;
      fs.writeFileSync(extensionPackageJsonPath, JSON.stringify(extPkg, null, 2) + '\n', 'utf8');
    } catch {
      // ignore
    }
  }

  // 7. extension manifests (Chromium, Firefox, Safari)
  const manifests = [extensionChromiumManifestPath, extensionFirefoxManifestPath, extensionSafariManifestPath];
  for (const mPath of manifests) {
    if (fs.existsSync(mPath)) {
      try {
        const manifest = JSON.parse(fs.readFileSync(mPath, 'utf8'));
        manifest.version = versionString;
        fs.writeFileSync(mPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
      } catch {
        // ignore
      }
    }
  }

  // 9. laterbox-ios/laterbox-ios.xcodeproj/project.pbxproj (Native iOS app and extension targets)
  if (fs.existsSync(iosPbxprojPath)) {
    try {
      let pbx = fs.readFileSync(iosPbxprojPath, 'utf8');
      pbx = pbx.replace(/MARKETING_VERSION\s*=\s*[^;]+;/g, `MARKETING_VERSION = ${versionString};`);
      pbx = pbx.replace(/CURRENT_PROJECT_VERSION\s*=\s*[^;]+;/g, `CURRENT_PROJECT_VERSION = ${buildNumber};`);
      fs.writeFileSync(iosPbxprojPath, pbx, 'utf8');
    } catch (err) {
      console.warn('[LaterBox Version] Warning: Failed to update project.pbxproj:', err.message);
    }
  }

  // 10. laterbox-ios/LaterBoxShare/Info.plist
  if (fs.existsSync(iosShareInfoPlistPath)) {
    try {
      let shareInfo = fs.readFileSync(iosShareInfoPlistPath, 'utf8');
      shareInfo = shareInfo.replace(/<key>CFBundleShortVersionString<\/key><string>[^<]+<\/string>/g, '<key>CFBundleShortVersionString</key><string>$(MARKETING_VERSION)</string>');
      shareInfo = shareInfo.replace(/<key>CFBundleVersion<\/key><string>[^<]+<\/string>/g, '<key>CFBundleVersion</key><string>$(CURRENT_PROJECT_VERSION)</string>');
      fs.writeFileSync(iosShareInfoPlistPath, shareInfo, 'utf8');
    } catch (err) {
      console.warn('[LaterBox Version] Warning: Failed to update LaterBoxShare Info.plist:', err.message);
    }
  }

  // 11. laterbox-ios/laterbox-ios/AppVersion.swift (Native Swift Version Constants & Runtime Helper)
  if (fs.existsSync(path.dirname(iosAppVersionSwiftPath))) {
    const swiftContent = `// Auto-generated by scripts/bump_version.js on every build/deploy
import Foundation

/// Provides compile-time version metadata and dynamic bundle introspection for LaterBox iOS.
public enum AppVersion {
    public static let marketingVersion = "${versionString}"
    public static let buildNumber = "${buildNumber}"
    public static let buildTime = "${buildTime}"

    /// Live version string from bundle (CFBundleShortVersionString), falling back to compile-time constant
    public static var currentVersion: String {
        (Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String) ?? marketingVersion
    }

    /// Live build number from bundle (CFBundleVersion), falling back to compile-time constant
    public static var currentBuild: String {
        (Bundle.main.infoDictionary?["CFBundleVersion"] as? String) ?? buildNumber
    }

    /// Clean formatted string for settings and diagnostics: "Version X.Y.Z (Build N)"
    public static var displayString: String {
        "Version \\(currentVersion) (Build \\(currentBuild))"
    }
}
`;
    fs.writeFileSync(iosAppVersionSwiftPath, swiftContent, 'utf8');
  }

  console.log(`[LaterBox Version] Synchronized version across iOS, Web, Extensions & Desktop: v${versionString} (build #${buildNumber})`);
}

bumpVersion();
