// Auto-generated by scripts/bump_version.js on every build/deploy
import Foundation

/// Provides compile-time version metadata and dynamic bundle introspection for LaterBox iOS.
public enum AppVersion {
    public static let marketingVersion = "1.0.174"
    public static let buildNumber = "176"
    public static let buildTime = "2026-10-06T21:18:37.889Z"

    /// Live version string from bundle (CFBundleShortVersionString), falling back to compile-time constant
    public static var currentVersion: String {
        (Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String) ?? marketingVersion
    }

    /// Live build number from bundle (CFBundleVersion), falling back to compile-time constant
    public static var currentBuild: String {
        (Bundle.main.infoDictionary?["CFBundleVersion"] as? String) ?? buildNumber
    }

    /// Clean formatted string for settings and diagnostics: "Version X.Y.Z (Build N)"
    public static var displayString: String {
        "Version \(currentVersion) (Build \(currentBuild))"
    }
}
